version: '3.8'

services:
  fastapi-production-tracker:
    build: .
    ports:
      - "80:80"
    environment:
      - DB_UID=${DB_UID:-gpao}
      - DB_PWD=${DB_PWD:-flat}
      - DB_HOST=${DB_HOST:-192.168.1.200:2638}
      - DB_SERVER_NAME=${DB_SERVER_NAME:-excalib}
      - DB_DATABASE_NAME=${DB_DATABASE_NAME:-excalib}
    volumes:
      - ./.env:/app/.env:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:80/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - production-tracker-network
    command:
      ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]

networks:
  production-tracker-network:
    driver: bridge
